-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 21:17:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 9256_sispmscore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 9256_sispmscore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `9256_sispmscore` DEFAULT CHARACTER SET utf8 ;
USE `9256_sispmscore` ;

-- -----------------------------------------------------
-- Table `9256_sispmscore`.`tiposetor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`tiposetor` (
  `idtipo_setor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_setorcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_setor`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`setor` (
  `idsetor` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `telefone1` VARCHAR(100) NULL DEFAULT NULL,
  `telefone2` VARCHAR(100) NULL DEFAULT NULL,
  `cep` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` VARCHAR(255) NULL DEFAULT NULL,
  `longitude` VARCHAR(255) NULL DEFAULT NULL,
  `gestor` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_setor_idtipo_setor` INT(11) NOT NULL,
  PRIMARY KEY (`idsetor`),
  INDEX `fk_setor_tipo_setor_idx` (`tipo_setor_idtipo_setor` ASC) VISIBLE,
  CONSTRAINT `fk_setor_tipo_setor`
    FOREIGN KEY (`tipo_setor_idtipo_setor`)
    REFERENCES `9256_sispmscore`.`tiposetor` (`idtipo_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `setor_idsetor` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_setor1_idx` (`setor_idsetor` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `9256_sispmscore`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`anotacoes_setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`anotacoes_setor` (
  `idanotacoes` INT(11) NOT NULL AUTO_INCREMENT,
  `nota` VARCHAR(255) NULL DEFAULT NULL,
  `setor_idsetor` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idanotacoes`),
  INDEX `fk_anotacoes_setor1_idx` (`setor_idsetor` ASC) VISIBLE,
  INDEX `fk_anotacoes_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_anotacoes_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `9256_sispmscore`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anotacoes_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `9256_sispmscore`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`cargo` (
  `idcargo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`ocorrencia` (
  `idocorrencia` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` INT(11) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idocorrencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`prestadora_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`prestadora_servico` (
  `idprestadora_servico` INT(11) NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj` VARCHAR(100) NULL DEFAULT NULL,
  `telefone1` VARCHAR(100) NULL DEFAULT NULL,
  `telefone2` VARCHAR(100) NULL DEFAULT NULL,
  `cep` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idprestadora_servico`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`colaborador` (
  `idcolaborador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `data_admissao` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `setor_idsetor` INT(11) NOT NULL,
  `cargo_idcargo` INT(11) NOT NULL,
  `ocorrencia_idocorrencia` INT(11) NOT NULL,
  `prestadora_servico_idprestadora_servico` INT(11) NOT NULL,
  PRIMARY KEY (`idcolaborador`),
  INDEX `fk_colaborador_setor1_idx` (`setor_idsetor` ASC) VISIBLE,
  INDEX `fk_colaborador_cargo1_idx` (`cargo_idcargo` ASC) VISIBLE,
  INDEX `fk_colaborador_ocorrencia1_idx` (`ocorrencia_idocorrencia` ASC) VISIBLE,
  INDEX `fk_colaborador_prestadora_servico1_idx` (`prestadora_servico_idprestadora_servico` ASC) VISIBLE,
  CONSTRAINT `fk_colaborador_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `9256_sispmscore`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_ocorrencia1`
    FOREIGN KEY (`ocorrencia_idocorrencia`)
    REFERENCES `9256_sispmscore`.`ocorrencia` (`idocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_prestadora_servico1`
    FOREIGN KEY (`prestadora_servico_idprestadora_servico`)
    REFERENCES `9256_sispmscore`.`prestadora_servico` (`idprestadora_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `9256_sispmscore`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`historico` (
  `idhistorico` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  `colaborador_idcolaborador` INT(11) NOT NULL,
  `setor_idsetor` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `fk_historico_colaborador1_idx` (`colaborador_idcolaborador` ASC) VISIBLE,
  INDEX `fk_historico_setor1_idx` (`setor_idsetor` ASC) VISIBLE,
  INDEX `fk_historico_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_historico_colaborador1`
    FOREIGN KEY (`colaborador_idcolaborador`)
    REFERENCES `9256_sispmscore`.`colaborador` (`idcolaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `9256_sispmscore`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `9256_sispmscore`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `9256_sispmscore`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `9256_sispmscore`.`professor` (
  `idprofessor` INT(11) NOT NULL AUTO_INCREMENT,
  `segmento` VARCHAR(45) NULL DEFAULT NULL,
  `ano_escolarizacao` VARCHAR(45) NULL DEFAULT NULL,
  `turno` VARCHAR(45) NULL DEFAULT NULL,
  `turma` VARCHAR(45) NULL DEFAULT NULL,
  `matricula` VARCHAR(45) NULL DEFAULT NULL,
  `professor` VARCHAR(255) NULL DEFAULT NULL,
  `disciplina` VARCHAR(255) NULL DEFAULT NULL,
  `setor_idsetor` INT(11) NOT NULL,
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_setor1_idx` (`setor_idsetor` ASC) VISIBLE,
  CONSTRAINT `fk_professor_setor1`
    FOREIGN KEY (`setor_idsetor`)
    REFERENCES `9256_sispmscore`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
